name: Taxonomy build
on:
  workflow_dispatch:
  push:

env:
  TAX_NAME: jenv_taxonomy_2024

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build Taxonomy package
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p build

      - uses: montudor/action-zip@v1
        with: # recursive, archive name and path without extension, what to archive
          args: zip -r build/${{ env.TAX_NAME }}  ./${{ env.TAX_NAME }}

      - uses: actions/upload-artifact@master
        id: artifact-upload-step
        with:
          name: ${{ env.TAX_NAME }}-artifact
          path: build/${{ env.TAX_NAME }}.zip

      - name: Get the URL of the artifact
        run: |
          echo 'Artifact URL is ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}'

      - name: Is it
        run: |
          echo "${{ secrets.PAT }}"

      - name: Ping Integration
        env:
          archive_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}
        run: |
          type="trigger-workflow"
          
          curl -L \
            -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/xiffy/sbr.nl-web/actions/workflows/integration.yaml/dispatches \
          -d '{"ref":"${{ github.repository }}", "client_payload": {"branch": "main", "taxonomy": "${{ github.repository }}", "artifact_url": "${{ env.archive_url }}" }}'
