name: Taxonomy build
on:
  workflow_dispatch:
  push:

env:
  TAX_NAME: jenv_taxonomy_2024

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build Taxonomy package
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p build
      - uses: montudor/action-zip@v1
        with: # recursive, archive name and path without extension, what to archive
          args: zip -r build/${{ env.TAX_NAME }}  ./${{ env.TAX_NAME }}

      - uses: actions/upload-artifact@master
        id: artifact-upload-step
        with:
          name: ${{ env.TAX_NAME }}-artifact
          path: build/${{ env.TAX_NAME }}.zip

      - name: Get the URL of the artifact
        run:  echo 'Artifact URL is ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}'
